language: node_js
node_js:
  - "4.1"
install:
  - npm install phantomjs
  - npm install mocha-phantomjs
  - npm install
before_script:
  - phantomjs --version
  - mocha-phantomjs --version
  - gulp compile-coffee &
  - sleep 5
script:
  - mocha-phantomjs test/index.html
