language: node_js
node_js:
  - "0.10"
install:
  - npm install phantomjs
  - npm install https://github.com/metaskills/mocha-phantomjs/archive/v3.5.3.tar.gz
  - npm install
before_script:
  - phantomjs --version
  - mocha-phantomjs --version
script:
  - mocha-phantomjs test/index.html